.PHONY: clean All

All:
	@echo "----------Building project:[ API-C-TEST - Debug ]----------"
	@cd "/Users/admin/Desktop/Github/MarioCode/API-C-TEST" && "$(MAKE)" -f  "API-C-TEST.mk"
clean:
	@echo "----------Cleaning project:[ API-C-TEST - Debug ]----------"
	@cd "/Users/admin/Desktop/Github/MarioCode/API-C-TEST" && "$(MAKE)" -f  "API-C-TEST.mk" clean
